package com.myspace.test_git_hook;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int newfield;

	private java.lang.String yes;

	private java.lang.String more;

	public test() {
	}

	public int getNewfield() {
		return this.newfield;
	}

	public void setNewfield(int newfield) {
		this.newfield = newfield;
	}

	public java.lang.String getYes() {
		return this.yes;
	}

	public void setYes(java.lang.String yes) {
		this.yes = yes;
	}

	public java.lang.String getMore() {
		return this.more;
	}

	public void setMore(java.lang.String more) {
		this.more = more;
	}

	public test(int newfield, java.lang.String yes, java.lang.String more) {
		this.newfield = newfield;
		this.yes = yes;
		this.more = more;
	}

}