package com.myspace.test_git_hook;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int newfield;

	private java.lang.String yes;

	private java.lang.String more;

	private java.lang.String finalone;

	private java.lang.Boolean worksnow;

	public test() {
	}

	public int getNewfield() {
		return this.newfield;
	}

	public void setNewfield(int newfield) {
		this.newfield = newfield;
	}

	public java.lang.String getYes() {
		return this.yes;
	}

	public void setYes(java.lang.String yes) {
		this.yes = yes;
	}

	public java.lang.String getMore() {
		return this.more;
	}

	public void setMore(java.lang.String more) {
		this.more = more;
	}

	public java.lang.String getFinalone() {
		return this.finalone;
	}

	public void setFinalone(java.lang.String finalone) {
		this.finalone = finalone;
	}

	public java.lang.Boolean getWorksnow() {
		return this.worksnow;
	}

	public void setWorksnow(java.lang.Boolean worksnow) {
		this.worksnow = worksnow;
	}

	public test(int newfield, java.lang.String yes, java.lang.String more,
			java.lang.String finalone, java.lang.Boolean worksnow) {
		this.newfield = newfield;
		this.yes = yes;
		this.more = more;
		this.finalone = finalone;
		this.worksnow = worksnow;
	}

}