#!/bin/bash
git ls-remote --exit-code upstream
if test $? != 0
then 
  REPO_URL=`git remote -v | grep -m1 '^origin' | sed -Ene's#.*(https://[^[:space:]]*).*#\1#p'`
  if [ -z "$REPO_URL" ]; then
    echo "-- ERROR:  Could not identify Repo url."
    echo "   It is possible this repo is already using SSH instead of HTTPS."
    exit
  fi

  USER=`echo $REPO_URL | cut -d/ -f4`
  if [ -z "$USER" ]; then
    echo "-- ERROR:  Could not identify User."
    exit
  fi

  REPO=`echo $REPO_URL | cut -d/ -f5`
  if [ -z "$REPO" ]; then
    echo "-- ERROR:  Could not identify Repo."
    exit
  fi

  NEW_URL="git@github.com:$USER/$REPO.git"
  
  git remote add upstream $NEW_URL
fi
  
BRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
echo "Current branch is ${BRANCH}"
git push upstream -u "${BRANCH}"
